2023-12-21 17:25:05.642 [info] Initial editor state {"filesToOpenOrCreate":[{"fileUri":{"$mid":1,"path":"/home/main/ms-toolsai.jupyter","scheme":"file"},"type":1,"exists":true,"options":{}},{"fileUri":{"$mid":1,"path":"/home/main/ms-python.python","scheme":"file"},"type":1,"exists":true,"options":{}}],"filesToDiff":[],"filesToMerge":[]}
2023-12-21 17:25:06.274 [info] Started local extension host with pid 821.
2023-12-21 17:25:06.351 [error] Extension 'ms-python.python CANNOT USE these API proposals 'contribEditorContentMenu, quickPickSortByLabel, testObserver, quickPickItemTooltip, saveEditor, terminalDataWriteEvent'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2023-12-21 17:25:06.451 [error] [ms-python.python]: editor/content is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["contribEditorContentMenu"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
2023-12-22 14:32:20.765 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 14:32:21.864 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 14:43:48.768 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 14:43:53.231 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 14:44:02.711 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 16:00:46.628 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at q.getLineContent (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:730:4396)
    at o.update (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:681:81713)
    at P.w (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:744:53935)
2023-12-22 16:19:37.408 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:19:40.287 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:32:44.025 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:33:41.885 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:33:43.494 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:36:44.287 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 16:36:54.565 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:42:41.458 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:42:52.224 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:42:55.384 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:43:15.458 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:43:37.238 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:43:39.071 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:44:26.646 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:44:27.661 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:44:47.034 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 18:56:42.781 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 19:03:41.823 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
2023-12-22 20:06:55.321 [error] ValueError: `column` parameter (69) is not in a valid range (0-68) for line 48 ('        # Not a FIR system is any column after last impulse does not\n').: Error: ValueError: `column` parameter (69) is not in a valid range (0-68) for line 48 ('        # Not a FIR system is any column after last impulse does not\n').
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
	at re (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
	at /home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
	at Immediate.<anonymous> (/home/main/.vscode-oss/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
	at process.processImmediate (node:internal/timers:476:21)
